# Generated by Django 3.0.6 on 2020-06-18 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='code',
            field=models.CharField(max_length=20, unique=True, verbose_name='Mã'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Tên'),
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Mã')),
                ('name', models.CharField(max_length=100, verbose_name='Tên')),
                ('price', models.IntegerField(verbose_name='Giá')),
                ('description', models.CharField(blank=True, max_length=300, verbose_name='Mô tả')),
                ('image', models.ImageField(blank=True, null=True, upload_to='static/images', verbose_name='Ảnh')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.Category', verbose_name='Nhóm sản phẩm')),
            ],
        ),
    ]
